### ISSUE TITLE
install DBD::Oracle from CPAN - various problems

### ISSUE THREAD

**Issue by otheus** [perl5-dbi/DBD-Oracle#47] opened 2017-07-18 15:50 UTC
```
Installing on a linux, Ver#2.6
Using Oracle in /usr/lib/oracle/12.2/client64
Can't find sqlplus. Pity, it would have helped.
I'm having trouble finding your Oracle version number... trying harder

WARNING: I could not determine Oracle client version so I'll just
default to version 8.0.0.0. Some features of DBD::Oracle may not work.
Oracle version based logic in Makefile.PL may produce erroneous results.
You can use "perl Makefile.PL -V X.Y.Z" to specify a your client version.

Oracle version 8.0.0.0 (8.0)
DBD::Oracle no longer supports Oracle client versions before 9.2
 Try a version before 1.25 for 9 and 1.18 for 8! at Makefile.PL line 271.
Warning: No success on command[/usr/bin/perl Makefile.PL]
'YAML' not installed, will not store persistent state
  PYTHIAN/DBD-Oracle-1.74.tar.gz
```

Seems this version should try for a higher default client version. It should also attempt to grok version number from ORACLE_HOME itself.

**Comment by mjegh** [comment] 2017-07-18 16:13
The Makefile looks for sqlplus and gets the version from that. If you've installed instant client and set LD_LIBRARY_PATH to point at it, it will all work fine.
If you look at the Makefile.PL you'll see it is very complicated and carries a lot of baggage from many many years of Oracle changes. It would be a brave man who alters Makefile.PL now.

**Comment by otheus** [comment] 2017-07-19 19:28
OK, so my general complaint is now: 
# the README file no longer points to useful information. 
# The INSTALL file is very hard to find unless one manually unpacks and looks for the file
# The install instructions in said file do not actually give tips for (1) which prerequesites need to be installed ie (client-sdk, slient-sqlplus), (2) what environment variables need to be set and how (ie, ORACLE_HOME)
# Other / OLD Readme/install tips suggest "sqlplus is optional" which is obviously no longer the case.
# the .mk file in 12.2 has been moved and is no longer findable without hacks (copying files around). 

I'd proffer to fix but my patch-stack is enormous.

**Comment by whindsx** [comment] 2017-07-19 20:10
6. On Solaris 11 you have to update the Makefile by hand to pick up the 64 bit libraries if that's what you want to use (in my case: /usr/oracle/instantclient/12.1/lib/64/)

I build DBD::Oracle fairly regularly and haven't had any luck installing with CPAN in about the last 6 attempts. This is includes fresh builds for Oracle Linux and Solaris 11.3. It seems if it should work on any platform it should work on Oracle's.

I'm fairly "brave" but only have the means for testing on Oracle Linux/Solaris with Oracle 12+ server. That being said, I'll see what I can do for 5 and 6.

Btw on 5 there's a switch for the .mk file:
$ perl Makefile.PL -m /usr/oracle/instantclient/12.1/sdk/demo/demo.mk
But yes, it should get picked up automatically with CPAN and doesn't.

**Comment by mjegh** [comment] 2017-07-20 08:36
otheus, I was only trying to help you. FYI You can complain all you like but it is probably not going to get you anywhere as although DBD::Oracle has an official maintainer he is not doing anything. I am a co-maintainer and released a few development releases but when my patches were not released officially I gave up and I maintain my own DBD::Oracle. There is one massive patch of fixes and improvements contributed which I cannot merge with my changes because it has got so out of date now.

The easiest way I find to install DBD::Oracle on unix is to install all the instant client zips, point LD_LIBRARY_PATH at the dir containing the instant client and run the Makefile.PL. Works every time for me.

**Comment by otheus** [comment] 2017-07-20 12:34
+mjegh Thanks. btdt. Frustration abounds. Anyway to take control of the project so that we can get back to a maintainable branch?
+whindsx Oracle is rightly to blame here also. For such a large company, and given that perl was one of the key reasons Oracle was happily adopted by Solaris admins, their poor ability to work with the perl community is shocking.

**Comment by otheus** [comment] 2017-07-21 13:11
So, 

## Installation

1. Install oracle client devel, basic, AND sqlplus. 
2. [Linux] Hack/copy the files into the "right place"
   sudo cp /usr/share/oracle/12.2/client64/demo/* /usr/share/oracle/12.2/client64
3. Set ORACLE_HOME accordingly.
4. `export LD_LIBRARY_PATH=$ORACLE_HOME/lib`
5. ``perl Makefile.pl; make``
6. Testing:
6.1. Create `$HOME/.tnsnames.ora` with `DB.TEST` pointing to some instance
6.2. `export ORACLE_DSN=dbi:Oracle:DB.TEST`
6.3. `export ORACLE_USERID=<username>/<password>`
6.4 `make test`

## Deployment

1. Install Oracle RPM for `basic`. 
2. Set `ORACLE_HOME/LD_LIBRARY_PATH` as above
4. Install CPAN files.

## RPM Deployment

(TBD)

**Comment by whindsx** [comment] 2017-08-01 14:00
@otheus Yes, when installing from CPAN version. If you clone from Github you should be able to skip the hack part.

@mjegh So you're saying that Pythian's branch is unfit for a CPAN release? To me the real issue is that nothing has been uploaded to CPAN since 2014.

**Comment by mjegh** [comment] 2017-08-01 14:26
@whindsx I'm nolonger sure of the state of the Pythian branch as no merges have happened for ages. I do know the large sponsored patch waiting for merge is worth having. I agree, the problem is the lack of activity and in part it will be argued I am part to blame as a co maintainer. I did what I could, when I could and if you look back at the change history I've submitted loads of patches and done some dev releases but it reached a point where I was having to expend too much energy for simple changes or my pull requests were ignored (there is more to it than this). I'm now stuck, as my own copy varies so much from the official one I can't even merge the large sponsored patch uploaded some time ago - too many conflicts I can't resolve.
The Pythian copy does have bugs fixed by the large patch I refer to and some other as well. However, unless you are doing something special (TAF etc), it works fine and is working fine in a major commercial application I am using.

**Comment by whindsx** [comment] 2017-10-17 18:56
So back to getting a CPAN release. Even if it lacks some features, I know for my shop it would be nice to get some of these build fixes into CPAN because we are doing deployments with Oracle Linux and Solaris (ya i know) where we install from CPAN.

@pythian is the CPAN user. Who typically uploads the distro? Need some help?

**Comment by djzort** [comment] 2020-09-03 07:30
We're releasing now, lets close this.

**Closed by djzort** 2020-09-03 07:30 UTC
